name: Deploy gh-pages

on:
  push:
    branches: 
      - 'dev_mondrian'  
      
env:
  GITHUB_SERVER: ${{ secrets.MONDRIAN_DRAWIO_GITHUB_URL }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev_mondrian
        #submodules: 'recursive'
        token: ${{ secrets.MONDRIAN_DRAWIO_TOKEN }}
    - name: Reset submodules recursively
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@${GITHUB_SERVER}/${GITHUB_REPOSITORY}.git
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions - reset submodules"
        git submodule foreach --recursive git reset --hard
        git submodule update --init --recursive --remote
        git add .
        git commit -m "Reset submodules" || echo "No changes to commit"
        git push
      env:
          GITHUB_TOKEN: ${{ secrets.MONDRIAN_DRAWIO_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install gh-pages
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@${GITHUB_SERVER}/${GITHUB_REPOSITORY}.git
        npm run page-deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
